=encoding utf8

=head1 NAME

Quiq::SoapWsdlServiceCgi::Demo - Demo für SOAP Web Service

=head1 BASE CLASS

L<Quiq::SoapWsdlServiceCgi|https://github.com/s31tz/Quiq/tree/master/pod/class/Quiq/SoapWsdlServiceCgi.pod>

=head1 METHODS

=head2 Service-Methoden

=head3 serverTime() - Liefere lokale Server-Zeit als Zeichenkette

=head4 Synopsis

  $time = $class->serverTime;

=head4 Wsdl

  _RETURN $string

=begin WSDL

  _RETURN $string

=end WSDL

=head1 VERSION

1.189

=head1 SOURCE

L<https://github.com/s31tz/Quiq/tree/master/lib/Quiq/SoapWsdlServiceCgi/Demo.pm>

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2020 Frank Seitz

=head1 LICENSE

This code is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
