=encoding utf8

=head1 NAME

Quiq::TeX::Code - Generator für TeX Code

=head1 BASE CLASS

L<Quiq::Hash|https://github.com/s31tz/Quiq/tree/master/pod/class/Quiq/Hash.pod>

=head1 DESCRIPTION

Ein Objekt der Klasse repräsentiert einen TeX Code-Generator. Mit
den Methoden der Klasse kann aus einem Perl-Programm heraus
TeX-Code erzeugt werden.

=head1 METHODS

=head2 Konstruktor

=head3 new() - Instantiiere TeX Code-Generator

=head4 Synopsis

    $t = $class->new;

=head4 Description

Instantiiere einen TeX Code-Generator und liefere eine Referenz
auf dieses Objekt zurück.

=head2 Objektmethoden

=head3 c() - Erzeuge TeX Codezeile

=head4 Synopsis

    $code = $t->c($fmt,@args,@opts);

=head4 Arguments

=over 4

=item $fmt

Codezeile mit sprintf Formatelementen.

=item @args

Argumente, die für die Formatelemente in $fmt eingesetzt
werden. Kommt eine Arrayreferenz vor, wird diese zu einem
kommaseparierten String expandiert.

=back

=head4 Options

=over 4

=item -nl => $n (Default: 1)

Beende den Code mit $n Zeilenumbrüchen.

=item -pnl => $n (Default: 0)

Beginne den Code mit $n Zeilenumbrüchen.

=back

=head4 Returns

TeX Code (String)

=head4 Description

Erzeuge eine TeX Codezeile und liefere das Resultat zurück.

=head4 Example

B<Makro mit Option und Parameter>

    $documentClass = 'article';
    $fontSize = '12pt';
    ...
    $t->c('\documentclass[%s]{%s}',$fontSize,$documentClass);

produziert

    \documentclass[12pt]{article}\n

B<Expansion von Array-Parameter>

    my @opt;
    push @opt,'labelsep=colon';
    push @opt,'labelfont=bf';
    push @opt,'skip=1.5ex';
    $t->c('\usepackage[%s]{caption}',\@opt);

produziert

    \usepackage[labelsep=colon,labelfont=bf,skip=1.5ex]{caption}

=head3 ci() - Erzeuge TeX Code inline

=head4 Synopsis

    $code = $t->ci($fmt,@args,@opts);

=head4 Arguments

=over 4

=item $fmt

Codezeile mit sprintf Formatelementen.

=item @args

Argumente, die in den Formatstring eingesetzt werden. Kommt unter
den Argumenten eine Arrayreferenz vor, wird diese zu einem
kommaseparierten String expandiert.

=back

=head4 Options

=over 4

=item -nl => $n (Default: 0)

Beende den Code mit $n Zeilenumbrüchen.

=back

=head4 Returns

TeX Code (String)

=head4 Description

Erzeuge TeX Code und liefere das Resultat zurück. Die Methode
ist identisch zu Methode $t->c(), nur dass per Default kein
Newline am Ende des Code hinzugefügt wird. Das C<i> im
Methodennamen steht für "inline".

=head4 Example

B<< Vergleich von $t->ci(), sprintf(), $t->c() >>

    $t->ci('\thead[%sb]{%s}','c','Ein Text');

ist identisch zu

    sprintf '\thead[%sb]{%s}','c','Ein Text';

ist identisch zu

    $t->c('\thead[%sb]{%s}','c','Ein Text',-nl=>0);

und produziert

    \thead[cb]{Ein Text}

=head3 macro() - Erzeuge TeX Macro

=head4 Synopsis

    $code = $t->macro($name,@args);

=head4 Options

=over 4

=item -nl => $n (Default: 1)

I<Newline>, füge $n Zeilenumbrüche am Ende hinzu.

=item -o => $options

=item -o => \@options

Füge eine Option/Optionsliste [...] hinzu. Ein Array wird in eine
kommaseparierte Liste von Werten übersetzt.

=item -p => $parameters

=item -p => \@parameters

Füge einen Parameter/eine Parameterliste {...} hinzu. Ein Array
wird in eine kommaseparierte Liste von Werten übersetzt.

=item -pnl => $n (Default: 0)

I<Preceeding newline>, setze $n Zeilenumbrüche an den Anfang.

=back

=head4 Description

Erzeuge ein TeX Macro und liefere den resultierenden Code
zurück. Diese Methode zeichnet sich gegenüber den Methoden $t->c()
und $t->ci() dadurch aus, dass undefinierte/leere Optionen und
Parameter vollständig weggelassen werden.

=head4 Examples

B<Macro ohne Argumente>

    $t->macro('\LaTeX');

produziert

    \LaTeX

B<Kommando mit undefiniertem Argument>

    $t->macro('\LaTeX',-p=>undef);

produziert

    \LaTeX

B<Macro mit Leerstring-Argument >

    $t->macro('\LaTeX',-p=>'');

produziert

    \LaTeX{}

B<Macro mit leerer Optionsliste und Parameter>

    @opt = ();
    $t->macro('\documentclass',-o=>\@opt,-p=>'article');

produziert

    \documentclass{article}

B<Macro mit Opton und Parameter>

    $t->macro('\documentclass',
        -o => '12pt',
        -p => 'article',
    );

produziert

    \documentclass[12pt]{article}

B<Macro mit Parameter und mehreren Optionen (Variante 1)>

    $t->macro('\documentclass',
        -o => 'a4wide,12pt',
        -p => 'article',
    );

produziert

    \documentclass[a4wide,12pt]{article}

B<Macro mit Parameter und mehreren Optionen (Variante 2)>

    @opt = ('a4wide','12pt');
    $t->macro('\documentclass',
        -o => \@opt,
        -p => 'article',
    );

produziert

    \documentclass[a4wide,12pt]{article}

=head3 comment() - Erzeuge TeX-Kommentar

=head4 Synopsis

    $code = $l->comment($text,@opt);

=head4 Options

=over 4

=item -nl => $n (Default: 1)

Füge $n Zeilenumbrüche am Ende hinzu.

=item -pnl => $n (Default: 0)

Setze $n Zeilenumbrüche an den Anfang.

=back

=head4 Description

Erzeuge einen TeX-Kommentar und liefere den resultierenden Code
zurück.

=head4 Examples

B<Kommentar erzeugen>

    $l->comment("Dies ist\nein Kommentar");

produziert

    % Dies ist
    % ein Kommentar

=head3 modifyLength() - Wende Berechnung auf Länge an

=head4 Synopsis

    $newLength = $l->modifyLength($length,$expr);

=head4 Arguments

=over 4

=item $length

Eine einfache TeX-Länge. Beispiel: '1ex'.

=item $expr

Ein arithmetischer Ausdruck, der auf den Zahlenwert der Länge
angewendet wird. Beispiel: '*2' (multipliziere Länge mit 2).

=back

=head4 Returns

TeX-Länge (String)

=head4 Description

Wende den arithmetischen Ausdruck $expr auf TeX-Länge $length an
und liefere das Resultat zurück. Leerstring oder C<undef> werden
unverändert geliefert.

=head4 Example

    $l->modifyLength('1.5ex','*1.5');
    # 2.25ex

=head3 toLength() - Wandele Länge in TeX-Länge

=head4 Synopsis

    $length = $this->toLength($val);

=head4 Arguments

=over 4

=item $val

Länge, die in die TeX-Länge umgerechnet wird.

=back

=head4 Returns

TeX-Länge (String)

=head4 Examples

Keine Angabe:

    $class->toLength(undef);
    # undef

Angabe in Pixeln ohne Einheit:

    $class->toLength(100);
    # '75pt'

Angabe in Pixeln mit Einheit:

    $class->toLength('100px');
    # '75pt'

Alle anderen Werte bleiben unverändert:

    $class->toLength($val);
    # $val

=head1 VERSION

1.132

=head1 SOURCE

L<https://github.com/s31tz/Quiq/tree/master/lib/Quiq/TeX/Code.pm>

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2019 Frank Seitz

=head1 LICENSE

This code is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
