=encoding utf8

=head1 NAME

Quiq::StreamServe::Stream - Inhalt einer StreamServe Stream-Datei

=head1 BASE CLASS

L<Quiq::Hash|https://github.com/s31tz/Quiq/tree/master/pod/class/Quiq/Hash.pod>

=head1 DESCRIPTION

Ein Objekt der Klasse repräsentiert den Inhalt einer StreamServe
Stream-Datei:

=over 2

=item *

Feldwerte können abgfragt werden

=item *

Über den Blöcken kann iteriert werden

=back

=head1 METHODS

=head2 Klassenmethoden

=head3 new() - Instantiiere Objekt

=head4 Synopsis

  $ssf = $class->new($file,%options);

=head4 Arguments

=over 4

=item $file

Pfad der Streamdatei.

=back

=head4 Options

=over 4

=item -debug => $bool (Default: 0)

Gib den Inhalt des Streams auf STDOUT aus (Blöcke in Lesereihenfolge,
Felder alphanumerisch sortiert).

=item -ignore => \@vals (Default: [])

Feldwerte, die auf einen Leerstring reduziert werden. Beispiel:

  -ignore => ['.','*','-']

=back

=head4 Returns

Objekt

=head4 Description

Instantiiere ein Objekt der Klasse und liefere dieses zurück.
Enthält die Streamdatei mehr als einen Stream, wird eine Exception
geworfen.

=head3 lookup() - Suche Feld

=head4 Synopsis

  $val = $class->lookup($file,$name);

=head4 Arguments

=over 4

=item $file

Stream-Datei

=item $name

Name des gesuchten Feldes

=back

=head4 Returns

(String) Wert oder C<undef>

=head4 Description

Durchsuche den Stream $file nach dem ersten Vorkommen des Feldes $name
und liefere dessen Wert zurück. Kommt das Feld im Stream nicht vor,
liefere C<undef>.

=head3 lookupHeader() - Suche Feld im Header

=head4 Synopsis

  $val = $class->lookupHeader($file,$name);

=head4 Arguments

=over 4

=item $file

Stream-Datei

=item $name

Name des gesuchten Feldes

=back

=head4 Returns

(String) Wert oder C<undef>

=head4 Description

Durchsuche den Header des Streams $file nach dem ersten Vorkommen des
Feldes $name und liefere dessen Wert zurück. Kommt das Feld im Stream
nicht vor, liefere C<undef>. Die Felder des Headers beginnen mit einem
Stern (C<*>). Gegenüber Metjode lookup() ist die Methode lookupHeader()
effizienter, da sie nach Lesen der Headerfelder stoppt.

=head3 numberOfStreams() - Anzahl der (Einzel-)Streams

=head4 Synopsis

  $n = $class->numberOfStreams($file);

=head4 Arguments

=over 4

=item $file

Stream-Datei

=back

=head4 Returns

(Integer) Anzahl der Einzelstreams

=head4 Description

Ermittele die Anzahl der Einzelstreams und liefere diese zurück.
Ax-Streams zählen wir nicht mit.

=head3 split() - Zerlege (Multi-)Stream in Einzelstreams

=head4 Synopsis

  @arr | $arrA = $class->split($file);
  @arr | $arrA = $class->split(\$data);

=head4 Arguments

=over 4

=item $file

Stream-Datei

=item $data

Stream-Daten

=back

=head4 Returns

(Array of Strings) Liste der Einzelstreams

=head4 Description

Zerlege einen (Multi-)Stream (aus Datei oder In-Memory-Daten)
in Einzelstreams und liefere die Liste der Einzelstreams zurück.

Ax-Streams ignorieren wir. D.h. die gelieferte Liste ist leer, wenn der
Stream lediglich einen A0- oder A1-Stream enthält.

=head2 Objektmethoden

=head3 allBlocks() - Liste aller Blöcke

=head4 Synopsis

  @arr | $arrH = $ssf->allBlocks;

=head4 Returns

(Array of Hashes) Liste von Blöcken

=head4 Description

Liefere die Liste aller Blöcke des Streams.

=head3 blocks() - Liste der Blöcke einer Blockart

=head4 Synopsis

  @arr | $arrH = $ssf->blocks($prefix);
  @arr | $arrH = $ssf->blocks($prefix,$sloppy);

=head4 Arguments

=over 4

=item $prefix

Die Blockart

=back

=head4 Options

=over 4

=item $sloppy

Wenn gesetzt, wirf keine Exception, wenn die Blockart nicht existiert,
sondern liefere eine leere Liste.

=back

=head4 Returns

(Array of Hashes) Liste von Blöcken

=head4 Description

Liefere die Liste der Blöcke einer Blockarten. Eine Blockart ist durch
ihren Präfix charakterisiert.

=head3 file() - Pfad der Streamdatei (Accessor-Methode)

=head4 Synopsis

  $path = $ssf->file;

=head4 Returns

(String) Pfad der Streamdatei

=head4 Description

Liefere den Pfad der Streamdatei.

=head3 get() - Liefere Wert

=head4 Synopsis

  $val = $ssf->get($name,$i);
  $val = $ssf->get($name);

=head4 Arguments

=over 4

=item $name

Name des abzufragenden Feldes

=item $i (Default: 0)

Index im Falle mehrfachen Vorkommens des Feldes

=back

=head4 Returns

(String) Wert

=head3 prefixes() - Liste der Blockarten (Präfixe)

=head4 Synopsis

  @arr | $arrH = $ssf->prefixes;

=head4 Returns

(Array of Strings) Liste der Block-Präfixe

=head4 Description

Liefere die Liste der Blockarten. Eine Blockart ist durch die Liste
der gemeinsamen Feldpräfixe charakterisiert.

=head3 report() - Liefere Bericht über den Stream

=head4 Synopsis

  $text = $ssf->report;

=head4 Returns

(String) Text des Berichts

=head4 Description

Erzeuge einen Bericht über den Stream und liefere dessen Text zurück.

=head3 try() - Liefere Wert

=head4 Synopsis

  $val = $ssf->try($name,$i);
  $val = $ssf->try($name);

=head4 Arguments

=over 4

=item $name

Name des abzufragenden Feldes

=item $i (Default: 0)

Index im Falle mehrfachen Vorkommens des Feldes

=back

=head4 Returns

(String) Wert

=head4 Description

Wie get(), nur dass der Zugriff auf ein nicht-existentes Feld nicht
zu einer Exception führt, sondern C<undef> geliefert wird.

=head3 type() - Typ des Streams

=head4 Synopsis

  $type = $ssf->type;
  $type = $class->type($file);

=head4 Arguments

=over 4

=item $file

Stream-Datei

=back

=head4 Returns

(String) Typ des Stream, z.B. C<SOS1890H>

=head4 Description

Liefere den Typ der Streamdatei $ssf bzw. $file. Als Klassenmethode
gerufen, wird der Typ effizient ermittelt, ohne den ganzen Stream
einzulesen.

=head1 VERSION

1.233

=head1 SOURCE

L<https://github.com/s31tz/Quiq/tree/master/lib/Quiq/StreamServe/Stream.pm>

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2025 Frank Seitz

=head1 LICENSE

This code is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
