=encoding utf8

=head1 NAME

Quiq::ColumnFormat - Format einer Text-Kolumne

=head1 BASE CLASS

L<Quiq::Object|https://github.com/s31tz/Quiq/tree/master/pod/class/Quiq/Object.pod>

=head1 DESCRIPTION

Ein Objekt der Klasse ist Träger von Formatinformation über einer
Menge von Werten, die tabellarisch dargestellt werden sollen,
z.B. in einer Text- oder HTML-Tabelle.

Die Methoden der Klasse formatieren die Werte der Wertemenge
entsprechend und liefern Information über die Ausrichtung.

=head1 METHODS

=head2 Konstruktor

=head3 new() - Instantiiere Objekt

=head4 Synopsis

    $fmt = $class->new($type,$width,$scale,$null,$mask);

=head4 Description

Die übergebenen Parameter enthalten folgende Information:

=over 4

=item $type

Typ ('t', 's', 'd' oder 'f').

=item $width

Länge des längsten Werts.

=item $scale

Maximale Anzahl an Nachkommastellen (im Falle von Werten vom
Typ f).

=item $null

Anzahl der Nullwerte.

=item $mask

Maximale Anzahl der zu maskierenden Zeichen bei einzeiliger
Darstellung. Maskiert werden die Zeichen \n, \r, \t, \0, \\.

=back

=head2 Akzessoren

=head3 width() - Breite des längsten Werts

=head4 Synopsis

    $width = $fmt->width;

=head2 Formatierung

=head3 asFixedWidthString() - Formatiere Wert auf feste Breite

=head4 Synopsis

    $str = $fmt->asFixedWidthString($value);

=head3 asTdContent() - Formatiere Wert für eine HTML td-Zelle

=head4 Synopsis

    $html = $fmt->asTdContent($value);

=head3 htmlAlign() - Horizontale Ausrichtung in HTML

=head4 Synopsis

    $align = $fmt->htmlAlign;

=head4 Description

Für numerische Kolumnen wird der Wert 'right' geliefert,
für Textkolumnen der Wert 'left';

=head1 VERSION

1.134

=head1 SOURCE

L<https://github.com/s31tz/Quiq/tree/master/lib/Quiq/ColumnFormat.pm>

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2019 Frank Seitz

=head1 LICENSE

This code is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
