=encoding utf8

=head1 NAME

Quiq::ContentProcessor - Prozessor für Abschnitts-Dateien

=head1 BASE CLASS

L<Quiq::Hash|https://github.com/s31tz/Quiq/tree/master/pod/class/Quiq/Hash.pod>

=head1 SYNOPSIS

  use Quiq::ContentProcessor;
  
  $cop = Quiq::ContentProcessor->new('.mytool');
  $cop->registerType('MyTool::A','a','A','A');
  $cop->registerType('MyTool::B','b','B','A');
  ...
  $cop->load(@paths)->commit;
  
  for my $ent ($cop->entities) {
      $cop->msg($ent->name);
  }

=head1 DESCRIPTION

Ein Objekt der Klasse repräsentiert einen Prozessor für
Entitäts-Dateien. Die Dateien bestehen aus einer Folge von
Abschnitten, die von einem Abschnitts-Parser (s. Klasse
Quiq::Section::Parser) geparsed und zu Abschnitts-Objekten
instantiiert werden.

Der Prozessor delegiert die Verarbeitung der Abschnitts-Objekte an
die per registerType() registierten Entitäts-Klassen
(Plugin-Schnittstelle). Diese bauen aus den Abschnitts-Objekten
Entitäts-Strukturen auf, aus denen die Ausgabedateien generiert
werden. Die Entitäts-Klassen sind nicht Teil des ContentProzessors.

Bei Anwendung der Operation L<commit|"commit() - Übertrage Änderungen in den Storage">() wird der Quelltext jeder
Entität gegen den Stand im Storage verglichen. Im Falle einer
Änderung wird die Entität als geändert gekennzeichnet, d.h. ihre
Ausgabedateien müssen neu generiert werden.

Das Resultat der Ausführung ist eine Menge von Entitäts-Objekten
plus ihrem Änderungs-Status. Die Menge der Entitäts-Objekte kann
mit der Methode L<entities|"entities() - Liste der geladenen Entities">() abgefragt werden.

=head2 Universelles Plugin

Ein I<Universelles Plugin> kann definiert werden, indem bei
L<registerType|"registerType() - Registriere Entitäts-Typ">() nur $pluginClass und $extension als Argumente
angegeben werden. An diese Plugin-Klasse werden alle
(Haupt-)Abschnitts-Objekte delegiert, für die kein Plugin
definiert ist. Logischerweise kann es höchstens ein Universelles
Plugin geben. Für ein Universelles Plugin findet keine
Attribut-Validierung in der Basisklassenmethode create() statt.
Das Konzept ist in erster Linie für allgemeine Programme
wie z.B. Testprogramme gedacht.

=head2 Ausgaben

Der Umfang an Ausgaben wird mit der Konstruktor-Option
-verbosity=>$level eingestellt. Default ist 1.

Die Methode msg() schreibt eine Ausgabe nach STDERR. Der erste
Parameter gibt den Verbosity-Level an. Ist dieser größer als der
eingestellte Verbosity-Level, unterbleibt die Ausgabe.

  $cop->msg(2,$text);

Ist kein Level angegeben, erfolgt die Ausgabe I<immer>:

  $cop->msg($text);

Der Meldungstext $text kann printf-Formatelemente enthalten, diese
werden wie bei printf durch die zusätzlich angegebenen Argumente
ersetzt:

  $cop->msg($text,@args);

=head1 EXAMPLES

Füge alle Entitäts-Definitionen im Storage zu einem einzigen
Datenstrom zusammen und schreibe diesen nach STDOUT (z.B. für
Refactoring):

  $cop->load->fetch('-');

Übertrage alle Entitäts-Definitionen im Storage in Verzeichnis $dir
(das Verzeichnis hat die gleiche Struktur wie das Verzeichnis def
im Storage):

  $cop->load->fetch->($dir);

Liste alle Entitäten vom Typ $type auf:

  $cop->load;
  for my $ent ($cop->entities($type)) {
      $cop->msg($ent->name);
  }

=head1 METHODS

=head2 Konstruktor

=head3 new() - Instantiiere ContentProcessor-Objekt

=head4 Synopsis

  $cop = $class->new($storage,@opt);

=head4 Arguments

=over 4

=item $storage

Das Storage-Verzeichnis, z.B. '.storage'.

=back

=head4 Options

=over 4

=item -verbosity => 0|1|2 (Default: 1)

Umfang der Laufzeit-Meldungen.

=back

=head4 Returns

ContentProcessor-Objekt

=head4 Description

Instantiiere ein ContentProcessor-Objekt und liefere eine Referenz
auf dieses Objekt zurück.

=head2 Storage

=head3 storage() - Pfad zum oder innerhalb des Storage

=head4 Synopsis

  $path = $cop->storage;
  $path = $cop->storage($subPath);

=head4 Arguments

=over 4

=item $subPath

Ein Sub-Pfad innerhalb des Storage.

=back

=head4 Returns

Pfad

=head4 Description

Liefere den Pfad des Storage, ggf. ergänzt um den Sub-Pfad
$subPath.

=head2 Plugins

=head3 registerType() - Registriere Entitäts-Typ

=head4 Synopsis

  $cop->registerType($pluginClass,$extension,$entityType,$sectionType,@keyVal);
  $cop->registerType($pluginClass,$extension); # universelles Plugin

=head4 Arguments

=over 4

=item $pluginClass

Name der Plugin-Klasse, z.B. 'Program::Shell'.

=item $extension

Datei-Erweiterung für Dateien dieses Typs, ohne Punkt, z.B. 'prg'.

=item $entityType

Entitätstyp-Bezeichner, z.B. 'Program' oder 'Class/Perl'.

=item $sectionType

Abschnitts-Bezeichner ohne Klammerung, z.B. 'Program'.

=item @keyVal

Abschnitts-Attribute, die über den Abschnitts-Bezeichner hinaus
den Dateityp kennzeichnen, z.B. Language=>'Perl'.

=back

=head4 Returns

nichts

=head4 Description

Registriere Plugin-Klasse $pluginClass für Abschnitts-Objekte
des Typs $sectionType und den Eigenschaften @keyVal.

Entsprechende Dateien werden an der Extension $extension erkannt.
Als Typ-Bezeichner für Entitäten dieses Typs vereinbaren wir
$entityType.

Die Plugin-Klasse wird automatisch geladen, falls sie noch nicht
vorhanden ist (sie kann für Tests also auch "inline", d.h. im
Quelltext des rufenden Code, definiert werden).

Die Plugin-Definition wird intern auf einem Hash-Objekt
gespeichert, das vom ContentProcessor mit den instantiierten
Entitäten verbunden wird.

Es kann auch ein I<Universelles Plugin> definiert werden (siehe
Abschnitt L<Universelles Plugin|"Universelles Plugin">).

=head3 entityTypes() - Liste der Abschnitts-Typen

=head4 Synopsis

  @types | $typeA = $cop->entityTypes;

=head4 Returns

Liste von Abschnitts-Typen. Im Skalarkontext eine Referenz auf die
Liste.

=head4 Description

Liefere die Liste der Abschnitts-Typen (Bezeichner), die per
registerType() registriert wurden.

=head3 plugin() - Ermittele Plugin zu Abschnitts-Objekt

=head4 Synopsis

  $plg = $cop->plugin($sec);

=head4 Arguments

=over 4

=item $sec

Abschnitts-Objekt

=back

=head4 Returns

Plugin-Objekt

=head4 Description

Ermittele das Plugin zu Abschnitts-Objekt $sec. Existiert
kein Plugin zu dem Abschnitts-Objekt, liefere C<undef>.

=head2 Operationen

=head3 init() - Erzeuge Storage

=head4 Synopsis

  $cop = $cop->init;

=head4 Returns

ContentProcessor-Objekt (für Method-Chaining)

=head4 Description

Erzeuge den Storage, falls er nicht existiert. Existiert er bereits,
hat der Aufruf keinen Effekt.

=head3 commit() - Übertrage Änderungen in den Storage

=head4 Synopsis

  $cop = $cop->commit(@opt);

=head4 Options

=over 4

=item -incomplete => $bool (Default: 0)

Lade fehlende Entitäten aus dem Storage nach anstatt sie zum
Löschen anzubieten.

=back

=head4 Returns

ContentProcessor-Objekt (für Method-Chaining)

=head4 Description

Vergleiche den Quelltext jeder Entität gegen den Quelltext im
Storage und übertrage etwaige Änderungen dorthin. Geänderte
Entitäten werden in der Datenbank als geändert gekennzeichnet.

=head3 load() - Lade Entitäts-Definitionen

=head4 Synopsis

  $cop = $cop->load;
  $cop = $cop->load(@paths);

=head4 Arguments

=over 4

=item @paths

Liste der Verzeichnisse und Dateien. Pfad '-' bedeutet STDIN.

=back

=head4 Returns

ContentProcessor-Objekt (für Method-Chaining)

=head4 Description

Lade die Entitäts-Dateien der Pfade @paths. Ist @path leer, also
kein Path angegeben, werden die Entitäts-Dateien aus dem Storage
geladen.

Die Methode kann beliebig oft aufgerufen werden, aber nur der
erste Aufruf lädt die Dateien. Alle weiteren Aufrufe sind
Null-Operationen.

=head3 fetchToDir() - Hole Entitäts-Definitionen aus dem Storage

=head4 Synopsis

  $cop = $cop->fetchToDir($dir,$layout,@opt);

=head4 Arguments

=over 4

=item $dir

Verzeichnis, in welches die Entitäts-Definitionen geschrieben
werden.

=item $layout

Bezeichnung für das Verzeichnis-Layout. Dieser Parameter wird von
filesToFetch() der Basisklasse nicht genutzt und ist daher hier
nicht dokumentiert. Siehe Dokumentation bei den Subklassen.

=back

=head4 Options

=over 4

=item -overwrite => $bool (Default: 0)

Stelle keine Rückfrage, wenn Verzeichnis $dir bereits existiert.

=back

=head4 Returns

ContentProcessor-Objekt (für Method-Chaining)

=head4 Description

Übertrage alle Entitäts-Definitionen in Verzeichnis $dir (oder
nach STDOUT, s.u.) gemäß Layout $layout. Per Differenzbildung wird
dabei ein konsistenter Stand hergestellt. Existiert Verzeichnis
$dir nicht, wird es angelegt. Andernfalls wird eine Rückfrage
gestellt, ob das Verzeichnis überschrieben werden soll (siehe
auch Option --overwrite).

Wird als Verzeichnis ein Bindestrich (-) angegeben, werden die
Entitäts-Definitionen nach STDOUT geschrieben.

Die Methode bezieht die zu schreibenden Dateien von der Methode
L<filesToFetch|"filesToFetch() - Liste der Dateien für fetch">(), an die der Parameter $layout weiter gereicht
wird. Die Methode kann in abgeleiteten Klassen überschrieben
werden, um andere Strukturen zu generieren.

=head2 Hilfsmethoden

=head3 filesToFetch() - Liste der Dateien für fetch

=head4 Synopsis

  @files = $cop->filesToFetch;
  @files = $cop->filesToFetch($layout);

=head4 Arguments

=over 4

=item $layout

Bezeichner für eine bestimmte Abfolge und/oder Inhalt der Dateien.

=back

=head4 Returns

Array mit zweielementigen Arrays

=head4 Description

Liefere die Liste der Dateien, die von den Methode L<fetchToDir|"fetchToDir() - Hole Entitäts-Definitionen aus dem Storage">()
und [ANCHOR NOT FOUND]() geschrieben werden. Jede Datei wird durch ein
zweielementiges Array repräsentiert, bestehend aus einem Datei-Pfad
sowie dem Datei-Inhalt. Der Datei-Inhalt kann als String oder
String-Referenz angegeben sein.

Diese (Basisklassen-)Methode liefert für jede Entität die
Datei-Definiton

  [$ent->entityFile, $ent->sourceRef]

Damit erzeugt die Methode fetch() die gleiche Struktur wie
der ContentProcessor im Storage-Verzeichnis def.

Die Methode kann in abgeleiteten Klassen überschrieben werden, um
die Verzeichnisstruktur zu ändern und/oder den Inhalt der Dateien
anders zusammenzustellen (z.B. mehrere Entity-Definitionen in
einer Datei zusammenzufassen). In abgeleiteten Klassen können
verschiedene Layouts durch das Argument $layout
unterschieden werden.

=head2 Eingabedateien

=head3 extensionRegex() - Regex zum Auffinden von Eingabe-Dateien

=head4 Synopsis

  $regex = $cop->extensionRegex;

=head4 Returns

Kompilierter Regex

=head4 Description

Liefere den regulären Ausdruck, der die Dateinamen matcht, die vom
ContentProcessor verarbeitet werden. Der Regex wird genutzt, wenn
ein I<Verzeichnis> nach Eingabe-Dateien durchsucht wird.

=head3 findFiles() - Finde Entitäts-Dateien in Verzeichnis

=head4 Synopsis

  @files | $fileA = $cop->findFiles($dir,@opt);

=head4 Arguments

=over 4

=item $dir

Verzeichnis, das nach Dateien durchsucht wird.

=back

=head4 Options

=over 4

=item -noDotPaths => $bool (Default: 0)

Lasse Pfade, deren letzte
Komponente mit einem Punkt beginnt, aus. Auf diese Weise
verhindern wir, dass Dot-Verzeichnissse durchsucht werden.

=back

=head4 Returns

Liste der Datei-Pfade (Strings). Im Skalarkontext eine Referenz
auf die Liste.

=head4 Description

Durchsuche Verzeichnis $dir nach Entitäts-Dateien unter Verwendung
des Regex, der von L<extensionRegex|"extensionRegex() - Regex zum Auffinden von Eingabe-Dateien">() geliefert wird.

=head3 parseFiles() - Parse Dateien zu Entitäten

=head4 Synopsis

  @entities | $entityA = $cop->parseFiles(@files);

=head4 Arguments

=over 4

=item @files

Liste der Dateien. '-' bedeutet STDIN.

=back

=head4 Returns

Liste der Entitäten. Im Skalarkontext eine Referenz auf die Liste.

=head3 processSubSection() - Verarbeite Sub-Abschnitt (abstrakt)

=head4 Synopsis

  $cop->processSubSection($fileEnt,$ent,$mainSec,$sec);

=head4 Arguments

=over 4

=item $fileEnt

Entität, die Träger des gesamten Quelltextes ist. Diese ist im
Quelltext mit [] gekennzeichnet.

=item $ent

Die aktuelle Entität. Kann identisch zu $fileEnt oder eine
Sub-Entität (z.B. (File) oder (ProgramClass)) sein.

=item $mainSec

Die Entität oder Sub-Entität, der die mit <> gekennzeichneten
Abschnitte zugeordnet werden.

=item $sec

Der aktuelle Abschnitt.

=back

=head4 Returns

nichts

=head2 Entitäten

=head3 entities() - Liste der geladenen Entities

=head4 Synopsis

  @entities | $entityA = $cop->entities;
  @entities | $entityA = $cop->entities($type);

=head4 Arguments

=over 4

=item $type

Abschnitts-Typ.

=back

=head4 Returns

Liste von Entitäten. Im Skalarkontext eine Referenz auf die Liste.

=head4 Description

Liefere die Liste aller geladenen Entities oder aller
geladenen Entities vom Typ $type. Bei der Abfrage der Entities
eines Typs werden die Entities nach Name sortiert geliefert.

=head2 Persistente Information

=head3 needsTestDb() - Persistenter Hash für Test-Status

=head4 Synopsis

  $h = $cop->needsTestDb;

=head4 Returns

Hash-Referenz (persistenter Hash)

=head4 Description

Liefere eine Referenz auf den persistenten Hash, der den Status
von Entitäten speichert.

=head3 needsUpdateDb() - Persistenter Hash für Entitäts-Status

=head4 Synopsis

  $h = $cop->needsUpdateDb;

=head4 Returns

Hash-Referenz (persistenter Hash)

=head4 Description

Liefere eine Referenz auf den persistenten Hash, der den Status
von Entitäten speichert.

=head2 Ausgabe von Information

=head3 info() - Informationszeile

=head4 Synopsis

  $str = $cop->info;

=head4 Returns

Zeichenkette

=head4 Description

Liefere eine Informationszeile mit statistischen Informationen, die
am Ende der Verarbeitung ausgegeben werden kann.

=head3 msg() - Gib Information aus

=head4 Synopsis

  $cop->msg($text,@args);
  $cop->msg($level,$text,@args);

=head4 Arguments

=over 4

=item $level

Der Verbosity-Level, ab dem die Information ausgegeben wird.

=item $text

Text, der ausgegeben werden soll.

=item @args

Argumente, die für printf-Platzhalter in $text eingesetzt werden.

=back

=head4 Returns

nichts

=head4 Description

Gib Information $text auf STDERR aus, wenn $level kleinergleich
dem beim Konstruktor vorgebenen Verbosity-Level ist. Der Text kann
printf-Platzhalter enthalten, die durch die Argumente @args
ersetzt werden.

Zusätzlich wird der Platzhalter %T durch die aktuelle Ausführungsdauer
in Sekunden ersetzt.

=head1 VERSION

1.176

=head1 SOURCE

L<https://github.com/s31tz/Quiq/tree/master/lib/Quiq/ContentProcessor.pm>

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2020 Frank Seitz

=head1 LICENSE

This code is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
