=encoding utf8

=head1 NAME

Quiq::SQLite - Operationen auf einer SQLite-Datenbank

=head1 BASE CLASS

L<Quiq::Object|https://github.com/s31tz/Quiq/tree/master/pod/class/Quiq/Object.pod>

=head1 METHODS

=head2 Klassenmethoden

=head3 exportDatabase() - Exportiere SQLite Datenbank in Verzeichnis

=head4 Synopsis

  $class->exportDatabase($dbFile,$exportDir);

=head4 Arguments

=over 4

=item $dbFile

SQLite Datenbank-Datei.

=item $exportDir

Verzeichnis, in das die Datenbank (Schema und Daten)
gesichert wird. Existiert das Verzeichnis nicht, wird es angelegt.

=back

=head4 Description

Exportiere den Inhalt der SQLite-Datenbank $dbFile in
Verzeichnis $exportDir.

=head4 Example

  Quiq::SQLite->export('~/var/myapp/myapp.db','/tmp/myapp');

=head3 exportData() - Exportiere SQLite Tabellendaten in Verzeichnis

=head4 Synopsis

  $class->exportData($dbFile,$exportDir);

=head4 Arguments

=over 4

=item $dbFile

SQLite Datenbank-Datei.

=item $exportDir

Verzeichnis, in das die Tabellendaten gesichert werden. Existiert das
Verzeichnis nicht, wird es angelegt.

=back

=head4 Description

Exportiere die Tabellendaten der SQLite-Datenbank $dbFile in
Verzeichnis $exportDir.

=head4 Example

  Quiq::SQLite->export('~/var/myapp/myapp.db','/tmp/myapp');

=head3 importDatabase() - Importiere SQLite Tabellendaten aus Verzeichnis

=head4 Synopsis

  $class->importDatabase($dbFile,$exportDir);

=head3 importData() - Importiere SQLite Datenbank aus Verzeichnis

=head4 Synopsis

  $class->importData($dbFile,$exportDir);

=head3 recreateDatabase() - Erzeuge SQLite Datenbank neu

=head4 Synopsis

  $class->recreateDatabase($dbFile,$sub);

=head4 Arguments

=over 4

=item $dbFile

SQLite Datenbank-Datei.

=item $sub

Refenz auf eine Subroutine, die das Schema auf einer I<leeren>
Datenbank erzeugt. Als Parameter wird $dbFile übergeben.

  $class->recreateDatabase('~/var/myapp/myapp.db',sub {
      my $dbPath = shift;
  
      my $db = %<Quiq::Database::Connection->new("dbi#sqlite:$dbPath",
          -utf8 => 1,
      );
  
      # via $db alle Schemaobjekte erzeugen,
      # aber keine Daten importieren!
      ...
  
      return;
  });

=back

=head4 Description

Erzeuge die Datenbank $dbFile in folgenden Schritten via
Subroutine $sub erstmalig oder neu:

=over 4

=item 1.

Exportverzeichnis anlegen (temporäres Verzeichnis, das nur im
Fehlerfall erhalten bleibt)

=item 2.

Tabellendaten in Exportverzeichnis exportieren

=item 3.

Datenbank $dbFile in Exportverzeichnis sichern

=item 4.

Datenbank $dbFile vollständig leeren

=item 5.

Schema via $sub neu erzeugen

=item 6.

die unter 2. exportierten Daten importieren

=item 7.

Exportverzeichnis löschen (falls in den Schritten 4. bis 6.
kein Fehler aufgetreten ist)

=back

=head1 VERSION

1.193

=head1 SOURCE

L<https://github.com/s31tz/Quiq/tree/master/lib/Quiq/SQLite.pm>

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2021 Frank Seitz

=head1 LICENSE

This code is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
