=encoding utf8

=head1 NAME

Quiq::Database::Cursor - Datenbank-Cursor

=head1 BASE CLASS

L<Quiq::Hash|https://github.com/s31tz/Quiq/tree/master/pod/class/Quiq/Hash.pod>

=head1 DESCRIPTION

Ein Objekt der Klasse repräsentiert das Resultat einer
Statement-Ausführung auf einer Relationalen Datenbank.

=head1 METHODS

=head2 Konstruktor/Destruktor

=head3 new() - Instantiiere Cursor

=head4 Synopsis

  $cur = $class->new(@keyVal);

=head4 Description

Instantiiere ein Cursor-Objekt mit den Attributen @keyVal
und liefere dieses zurück.

=head3 close() - Schließe Cursor

=head4 Synopsis

  $cur->close;

=head4 Alias

destroy()

=head4 Description

Schließe Cursor. Die Methode liefert keinen Wert zurück.

=head2 Akzessoren

=head3 bindVars() - Liefere Anzahl der Bind-Variablen

=head4 Synopsis

  $n = $cur->bindVars;

=head3 bindTypes() - Setze/Liefere Datentypen der Bind-Variablen

=head4 Synopsis

  @arr|$arr = $cur->bindTypes(@dataTypes);
  @arr|$arr = $cur->bindTypes;

=head3 db() - Liefere Datenbankverbindung

=head4 Synopsis

  $db = $cur->db;

=head3 hits() - Liefere Anzahl der getroffenen Datensätze

=head4 Synopsis

  $n = $cur->hits;

=head4 Description

Liefere die Anzahl der von einem INSERT, UPDATE oder DELETE
getroffenen Datesätze.

=head3 id() - Liefere Wert der Autoincrement-Kolumne

=head4 Synopsis

  $id = $cur->id;

=head4 Alias

insertId()

=head4 Description

Liefere den Wert der Autoinkrement-Kolumne nach einem INSERT.

=head3 rowOperation() - Liefere die Datensatz-Operation

=head4 Synopsis

  $op = $cur->rowOperation;

=head4 Description

Liefere die von save() durchgeführte Datensatz-Operation: 0, 'I', 'U'
oder 'D'.

=head3 rowClass() - Liefere Namen der Datensatz-Klasse

=head4 Synopsis

  $rowClass = $cur->rowClass;

=head3 stmt() - Liefere SQL-Statement

=head4 Synopsis

  $stmt = $cur->stmt;

=head4 Description

Liefere das SQL-Statement, wie es an das DBMS übermittelt und von
ihm ausgeführt wurde. Das von der Methode gelieferte Statement
kann von dem Statement, das beim Aufruf angegeben wurde, verschieden
sein, da ggf. interne Transformationsschritte auf das Statement
anwendet wurden.

=head3 titles() - Liefere Liste der Kolumnentitel

=head4 Synopsis

  @titles | $titlesA = $cur->titles;

=head4 Description

Liefere die Liste der Kolumnenwerte. Im Skalarkontext liefere
eine Referenz auf die Liste.

=head3 width() - Anzahl der Kolumnen

=head4 Synopsis

  $width = $cur->width;

=head4 Description

Liefere die Anzahl der Kolumnen.

=head2 Tests

=head3 fromCache() - Liefert der Cursor Datensätze aus dem Cache?

=head4 Synopsis

  $bool = $cur->fromCache;

=head4 Description

Liefere wahr, wenn der Cursor Datensätze aus dem Cache liefert,
andernfalls falsch.

=head3 isSelect() - Liefert der Cursor Datensätze?

=head4 Synopsis

  $bool = $cur->isSelect;

=head4 Description

Liefere wahr, wenn der Cursor Datensätze liefert,
andernfalls falsch.

=head2 Zeitmessung

=head3 startTime() - Liefere Startzeitpunkt der Statement-Ausführung

=head4 Synopsis

  $time = $cur->startTime;

=head3 execTime() - Liefere Dauer der Statement-Ausführung

=head4 Synopsis

  $time = $cur->execTime;

=head3 elapsed() - Liefere Dauer seit Start der Statement-Ausführung

=head4 Synopsis

  $time = $cur->elapsed;

=head4 Alias

time()

=head2 Bind

=head3 bind() - Binde Werte an Statement und führe Statement aus

=head4 Synopsis

  $cur2 = $cur->bind(@vals);

=head4 Description

Binde eine Liste von Werten an die Platzhalter eines zuvor
präparierten SQL-Statements und führe dieses Statement auf der
Datenbank aus. Die Anzahl der Werte muß ein Vielfaches der Anzahl der
Bind-Variablen sein.

=head2 Fetch

=head3 export() - Schreibe Datensätze in Datei

=head4 Synopsis

  $cur->export($file,@opt);

=head4 Arguments

=over 4

=item $file

Pfad der Datei. Im Falle von '-' STDOUT.

=back

=head4 Options

=over 4

=item -limit => $n (Default: 0)

Schreibe maximal $n Datensätze. 0 = Keine Begrenzung.

=item -titles => $bool (Default: 0)

Schreibe als erste Zeile die Kolumentitel.

=back

=head4 Description

Exportiere die Datenesätze des Cursors in Datei $file. Die Datensätze
werden im COPY-Format geschrieben, d.h. Kolumnentrenner ist C<\t> und
Zeilentrenner ist C<\n>.

=head3 fetch() - Liefere nächsten Datensatz der Ergebnismenge

=head4 Synopsis

  $row = $cur->fetch;

=head4 Description

Liefere den nächsten Datensatz aus der Ergebnismenge. Ist das Ende der
Ergebnismenge erreicht, liefere undef.

=head3 fetchAll() - Liefere gesamte Ergebnismenge

=head4 Synopsis

  @rows | $tab = $cur->fetchAll;
  @rows | $tab = $cur->fetchAll($autoClose);
  @rows | $tab = $cur->fetchAll($autoClose,$limit);

=head4 Arguments

=over 4

=item $autoClose (Default: 0)

Ist Parameter $autoClose angegeben und wahr, schließe den Cursor
automatisch.

=item $limit (Default: 0)

Fetche maximal $limit Datensätze. Falls 0, fetche alle Datensätze.

=back

=head4 Returns

Liste der Datensätze (List-Kontext) der ein Resultset-Objekt
(Skalar-Kontect).

=head4 Description

Liefere die Ergebnismenge als Liste von Datensätzen oder als
Tabelle. Ist der Parameter $autoClose angegeben und "wahr" schließe
den Cursor automatisch.

=head1 VERSION

1.233

=head1 SOURCE

L<https://github.com/s31tz/Quiq/tree/master/lib/Quiq/Database/Cursor.pm>

=head1 AUTHOR

Frank Seitz, L<http://fseitz.de/>

=head1 COPYRIGHT

Copyright (C) 2025 Frank Seitz

=head1 LICENSE

This code is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
